## 1.ndarray的特性
### 多维性

In [1]:
import numpy

In [2]:
arr = numpy.array(3)#零维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

3的维度为： 0


In [3]:
arr = numpy.array([1,2,3])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[1 2 3]的维度为： 1


In [ ]:
arr = numpy.array([[4,5,6],[1,2,3]])#2维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[[[4 5 6]
  [1 2 3]]]的维度为： 3


### 同质性

In [5]:
arr = numpy.array([1,"hello"])#不同数据类型会被转换成统一的数据类型
print(f"{arr}的数据类型为：",arr.dtype)

['1' 'hello']的数据类型为： <U11


### 2.ndarray属性

In [6]:
arr = numpy.array(3)
print("数组形状为：",arr.shape)
print("数组维度为：",arr.ndim)
print("元素的个数为：",arr.size)
print("元素的数据类型：",arr.dtype)

数组形状为： ()
数组维度为： 0
元素的个数为： 1
元素的数据类型： int32


In [7]:
arr_1 = numpy.array([1,2.5,3])
print("数组形状为：",arr_1.shape)
print("数组维度为：",arr_1.ndim)
print("元素的个数为：",arr_1.size)
print("元素的数据类型：",arr_1.dtype)

数组形状为： (3,)
数组维度为： 1
元素的个数为： 3
元素的数据类型： float64


In [8]:
arr_2 = numpy.array([[1,2,3],[4,5,6]])
print("数组形状为：",arr_2.shape)
print("数组维度为：",arr_2.ndim)
print("元素的个数为：",arr_2.size)
print("元素的数据类型：",arr_2.dtype)
print("元素的转置：",arr_2.T)

数组形状为： (2, 3)
数组维度为： 2
元素的个数为： 6
元素的数据类型： int32
元素的转置： [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray的创建

In [9]:
# 预定义形状

arr_zeros = numpy.zeros((2,3),dtype=int)
print("全零二维三列数组：\n",arr_zeros)

全零二维三列数组：
 [[0 0 0]
 [0 0 0]]


In [10]:
arr_ones = numpy.ones((2,3))
print("全一二维数组：\n",arr_ones)

全一二维数组：
 [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr_empty = numpy.empty((3,3)) 
print("空二维数组：\n",arr_empty)

空二维数组：
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr_pull = numpy.full((2,3),7)
print("全7二维数组：\n",arr_pull)

全7二维数组：
 [[7 7 7]
 [7 7 7]]


In [13]:
# 根据已有数组形状创建新数组
arr_empty_like = numpy.empty_like(arr_pull)
print("根据arr_pull形状创建的空数组：\n",arr_empty_like)
print("--- ----------------------------------------------")
arr_ones_like = numpy.ones_like(arr_pull)
print("根据arr_pull形状创建的全一数组：\n",arr_ones_like)
print("--- ----------------------------------------------")
arr_zeros_like = numpy.zeros_like(arr_pull)
print("根据arr_pull形状创建的全零数组：\n",arr_zeros_like)
print("--- ----------------------------------------------")
arr_full_like = numpy.full_like(arr_pull,9)
print("根据arr_pull形状创建的全9数组：\n",arr_full_like)

根据arr_pull形状创建的空数组：
 [[1895722416        448          0]
 [         0     131074 1818304623]]
--- ----------------------------------------------
根据arr_pull形状创建的全一数组：
 [[1 1 1]
 [1 1 1]]
--- ----------------------------------------------
根据arr_pull形状创建的全零数组：
 [[0 0 0]
 [0 0 0]]
--- ----------------------------------------------
根据arr_pull形状创建的全9数组：
 [[9 9 9]
 [9 9 9]]


In [14]:
#
arr_a = numpy.arange(1,10,2)
print("arange创建的数组：\n",arr_a)


arange创建的数组：
 [1 3 5 7 9]


In [15]:
#等间隔数列
arr_b = numpy.linspace(0,100,5)
print("linspace创建的数组：\n",arr_b)
print("--- ----------------------------------------------")
arr_b_arange = numpy.arange(0,101,25)
print("arange创建的等间隔数组：\n",arr_b_arange)

linspace创建的数组：
 [  0.  25.  50.  75. 100.]
--- ----------------------------------------------
arange创建的等间隔数组：
 [  0  25  50  75 100]


In [16]:
#对数等差数列
arr_c = numpy.logspace(0,3,2,base = 2)
print("logspace创建的数组：\n",arr_c)

logspace创建的数组：
 [1. 8.]


In [17]:
#特殊矩阵
#单位矩阵:对角线为1，其余元素为0的方阵
arr_eye = numpy.eye(3,4,dtype=int)
print("单位矩阵：\n",arr_eye)

单位矩阵：
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [18]:
# 对角矩阵：主对角线上元素非零，其余元素为零的方阵
arr_diag = numpy.diag([1,2,3,4])
print("对角矩阵：\n",arr_diag)

对角矩阵：
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [19]:
# 随机数矩阵
# 生成0-1之间均匀分布的随机数矩阵
arr_rand = numpy.random.rand(2,3)#二行三列
print("随机数矩阵：\n",arr_rand)

随机数矩阵：
 [[0.26311861 0.27102776 0.15994918]
 [0.40101209 0.68048973 0.07514698]]


In [20]:
# 生成指定区间的随机浮点数
arr_uniform = numpy.random.uniform(1,10,(2,3))#1-10 二行三列
print("均匀分布随机数矩阵：\n",arr_uniform)

均匀分布随机数矩阵：
 [[2.95741475 7.12634329 2.4280117 ]
 [5.70776445 6.41430778 6.89441726]]


In [21]:
# 生成指定区间的随机整数
arr_randint = numpy.random.randint(1,10,(2,3))#1-10 二行三列
print("随机整数矩阵：\n",arr_randint)

随机整数矩阵：
 [[8 5 7]
 [7 5 5]]


In [22]:
# 生成随机数（正态分布）-3 -  3
arr_randn = numpy.random.randn(2,3) #二行三列
print("正态分布随机数矩阵：\n",arr_randn)

正态分布随机数矩阵：
 [[ 1.0063115  -0.02529269  0.83412647]
 [-0.9204452   1.10485597  0.08987906]]


In [23]:
# 生成随机种子
numpy.random.seed(20)
arr_randint = numpy.random.randint(1,10,(2,3))#1-10 二行三列
print("设置随机种子后的随机整数矩阵：\n",arr_randint)

设置随机种子后的随机整数矩阵：
 [[4 5 7]
 [8 3 1]]


### 4,ndarray的数据类型
##### 布尔类型：bool
##### 整数类型：int
##### 浮点数类型：float
##### 复数类型：complex


In [ ]:
# 映射为对应类型 注意范围
arr = numpy.array([1,0,1,0,0], dtype=bool)
print(f"{arr}的数据类型为：",arr.dtype)

[ True False  True False False]的数据类型为： bool


### 5.索引与切片

In [26]:
arr = numpy.random.randint(1,100,30)
print("随机生成的整数数组为：\n",arr)

随机生成的整数数组为：
 [78 18 44 17 19 80 91 60 72 76 30 46  7 64 79 25 19 94 34 79 43 95  4 19
 71 53 23 15  5 28]


In [35]:
# 对一维数组进行切片 支持逻辑运算符
print(arr[:])#获取全部元素
print("-- ----------------------------------------------")
print(arr[slice(2,20,1)])
print("--- ----------------------------------------------")
print(arr[0:5])#从索引0到5(不包含5)步长默认为1
print("--- ----------------------------------------------")
print(arr[0:10:2])#从索引0到10(不包含10)步长为2
print("--- ----------------------------------------------")
print(arr[arr>10])#大于10的元素

[78 18 44 17 19 80 91 60 72 76 30 46  7 64 79 25 19 94 34 79 43 95  4 19
 71 53 23 15  5 28]
-- ----------------------------------------------
[44 17 19 80 91 60 72 76 30 46  7 64 79 25 19 94 34 79]
--- ----------------------------------------------
[78 18 44 17 19]
--- ----------------------------------------------
[78 44 19 91 72]
--- ----------------------------------------------
[78 18 44 17 19 80 91 60 72 76 30 46 64 79 25 19 94 34 79 43 95 19 71 53
 23 15 28]


In [37]:
arr = numpy.random.randint(1,100,(3,4))
print("随机生成的二维整数数组为：\n",arr)

随机生成的二维整数数组为：
 [[76  9  7 27]
 [80 83 79 11]
 [34 86 18 41]]


In [ ]:
print(arr[1,2])#获取第2行第3列元素
print("--- ----------------------------------------------")
print(arr[:,:])#获取所有行所有列元素
print("--- ----------------------------------------------")
print(arr[0:3,2:4])#获取第1到3行，第3到4列元素
print("--- ----------------------------------------------")
print(arr[2][arr[2] > 50])#获取第3行大于50的元素
print("--- ----------------------------------------------")

79
--- ----------------------------------------------
[[76  9  7 27]
 [80 83 79 11]
 [34 86 18 41]]
--- ----------------------------------------------
[[ 7 27]
 [79 11]
 [18 41]]
--- ----------------------------------------------
[86]
