## 1.ndarray的特性
### 多维性

In [1]:
import numpy

In [2]:
arr = numpy.array(3)#零维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

3的维度为： 0


In [3]:
arr = numpy.array([1,2,3])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[1 2 3]的维度为： 1


In [4]:
arr = numpy.array([[4,5,6],[1,2,3]])#1维数组
print(f"{arr}的维度为：",numpy.ndim(arr))

[[4 5 6]
 [1 2 3]]的维度为： 2


### 同质性

In [5]:
arr = numpy.array([1,"hello"])#不同数据类型会被转换成统一的数据类型
print(f"{arr}的数据类型为：",arr.dtype)

['1' 'hello']的数据类型为： <U11


### 2.ndarray属性

In [6]:
arr = numpy.array(3)
print("数组形状为：",arr.shape)
print("数组维度为：",arr.ndim)
print("元素的个数为：",arr.size)
print("元素的数据类型：",arr.dtype)

数组形状为： ()
数组维度为： 0
元素的个数为： 1
元素的数据类型： int32


In [7]:
arr_1 = numpy.array([1,2.5,3])
print("数组形状为：",arr_1.shape)
print("数组维度为：",arr_1.ndim)
print("元素的个数为：",arr_1.size)
print("元素的数据类型：",arr_1.dtype)

数组形状为： (3,)
数组维度为： 1
元素的个数为： 3
元素的数据类型： float64


In [ ]:
arr_2 = numpy.array([[1,2,3],[4,5,6]])
print("数组形状为：",arr_2.shape)
print("数组维度为：",arr_2.ndim)
print("元素的个数为：",arr_2.size)
print("元素的数据类型：",arr_2.dtype)
print("元素的转置：",arr_2.T)

数组形状为： (2, 3)
数组维度为： 2
元素的个数为： 6
元素的数据类型： int32
元素的转置： [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray的创建