##### 统计函数
##### 求和 计算平均值 计算中位数 标准差 
##### 方差 查找最大值 最小值 计算分位数 累积差 累积和


In [1]:
import numpy as np

In [ ]:
# 求和
arr = np.array([1, 2, 3, 4])
print(np.sum(arr))  # 输出: 10

In [ ]:
# 计算平均值
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # 输出: 2.5

In [ ]:
# 计算中位数
arr = np.array([1, 3, 2, 4, 5])
print(np.median(arr))  # 输出: 3.0

In [ ]:
#就算方差
arr = np.array([1, 2, 3, 4])
print(np.var(arr))  # 输出: 1.25

In [ ]:
# 计算标准差（方差的算数平法根 ）
arr = np.array([1, 2, 3, 4])
print(np.std(arr))  # 输出: 1.118033988749895

In [16]:
#计算分位数
arr = np.array([1, 2, 3, 4, 5])
print(np.percentile(arr, 75))  # 输出: 3.0

4.0


In [21]:
# 累积和
arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr))  # 输出: [ 1  3  6

[ 1  3  6 10]


In [ ]:
# 累积差
arr = np.array([1, 2, 3, 4])
# 步骤1：计算一阶差分（相邻差）
diff_arr = np.diff(arr)#输出:[1 1 1]
# 步骤2：对差分做累积和 → 累积差
cum_diff = np.cumsum(diff_arr)#输出:[1 2 3]
print(cum_diff)
print("--- ----------------------------------------------")
cum_diff_direct = arr[1:] - arr[0]#一步到位
print(cum_diff_direct)


[1 2 3]
[1 2 3]
--- ----------------------------------------------
[ 1  2  6 24]
[ 1  2  6 24]


In [23]:
# amain 计算最小值
arr = np.array([3, 7, 5, 9, 11])
print(np.amin(arr,axis=0))  # 计算最小值
print("--- ----------------------------------------------")
arr_a = np.array([[3, 7, 5], [9, 11, 2]])
print(np.amin(arr_a,axis=1))  # 按行计算最小
# 三维数组
arr_b = np.array([[[3, 7, 5], [9, 11, 2]], [[13, 17, 15], [19, 21, 12]]])
print("原数组：")
print(arr_b)
print("--- ----------------------------------------------")
print(np.amin(arr_b,axis=1)) 


3
--- ----------------------------------------------
[3 2]
原数组：
[[[ 3  7  5]
  [ 9 11  2]]

 [[13 17 15]
  [19 21 12]]]
--- ----------------------------------------------
[[ 3  7  2]
 [13 17 12]]


In [ ]:
# 计算最大值
arr = np.array([3, 7, 5, 9, 11])
print(np.amax(arr,axis=0))  # 计算最大值
print("--- ----------------------------------------------")
arr_a = np.array([[3, 7, 5], [9, 11, 2]])
print(np.amax(arr_a,axis=0))  # 按列计算最大
print(np.amax(arr_a,axis=1))  # 按行计算最大
print("--- ----------------------------------------------")

11
--- ----------------------------------------------
[ 9 11  5]
[ 7 11]



#### 比较函数
#### 比较是否大于 小于 等于 逻辑与 或 非

In [25]:
# 比较是否大于
arr = np.array([1, 2, 3, 4, 5])
print(np.greater(arr, 3))  # 输出: [False False False  True  True]
print("--- ----------------------------------------------")
# 比较是否小于
print(np.less(arr, 3))  # 输出: [ True  True False False False]
print("--- ----------------------------------------------")
# 比较是否等于
print(np.equal(arr, 3))  # 输出: [False False  True False False]

[False False False  True  True]
--- ----------------------------------------------
[ True  True False False False]
--- ----------------------------------------------
[False False  True False False]


In [27]:
# 自定义条件
arr = np.array([10, 15, 20, 25, 30])
print(np.where(arr > 10, arr, 0))  # 输出: [ 0 15 20 25 30]
print("--- ----------------------------------------------")

[ 0 15 20 25 30]
--- ----------------------------------------------


In [ ]:
#案例：将不及格成绩替换为"不及格"
score = np.random.randint(0, 101, size=10)
print("原始成绩：", score)
print("及格成绩：", np.where(score >= 60, score, "不及格"))  # 不及格的成绩替换为"不及格"

原始成绩： [53 90 65 82 59 99 55 14 40 49]
及格成绩： ['不及格' '90' '65' '82' '不及格' '99' '不及格' '不及格' '不及格' '不及格']


In [ ]:
# 逻辑与 一假全假
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True, False, False])
print(np.logical_and(arr1, arr2))  # 输出: [ True False False False]
print("--- ----------------------------------------------")
# 逻辑或 一真全真
print(np.logical_or(arr1, arr2))  # 输出: [ True True True False]
print("--- ----------------------------------------------")
# 逻辑非 取反
print(np.logical_not(arr1))  # 输出: [False  True False  True]

#### 排序函数

In [38]:
np.random.seed(0)  # 设置随机种子以获得可重复结果
arr = np.random.randint(1,100,size=10)
print("原始数组：", arr)
print("--- ----------------------------------------------")
# 从小到大排序
print(np.sort(arr))
print("--- ----------------------------------------------")
# 升序排列索引值
print(np.argsort(arr))
# 从大到小排序
print(np.sort(arr)[::-1])
#去重
print(np.unique(arr))

原始数组： [45 48 65 68 68 10 84 22 37 88]
--- ----------------------------------------------
[10 22 37 45 48 65 68 68 84 88]
--- ----------------------------------------------
[5 7 8 0 1 2 3 4 6 9]
[88 84 68 68 65 48 45 37 22 10]
[10 22 37 45 48 65 68 84 88]
